# Generated by Django 5.0.6 on 2026-03-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Propriétaire'), ('vet', 'Vétérinaire'), ('admin', 'Administrateur')], default='user', max_length=10),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='comptes_utilisateur',
        ),
    ]
