# Generated by Django 5.0.6 on 2026-04-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_last_seen_chatmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='comptes_cha_sender__3e1156_idx',
            old_name='comptes_cha_sender__idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='comptes_cha_recipie_891db3_idx',
            old_name='comptes_cha_recipie_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
