# Generated by Django 5.0.6 on 2026-04-20 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comptes_follow',
                'indexes': [models.Index(fields=['follower', '-created_at'], name='comptes_fol_followe_e8a22d_idx'), models.Index(fields=['following', '-created_at'], name='comptes_fol_followi_2b7394_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
