# Generated by Django 5.0.6 on 2026-04-25 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comptes_user_block',
                'indexes': [models.Index(fields=['blocker', '-created_at'], name='comptes_use_blocker_3a584c_idx'), models.Index(fields=['blocked', '-created_at'], name='comptes_use_blocked_046abe_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='userblock',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='comptes_user_block_blocker_blocked_uniq'),
        ),
    ]
