"""
Django settings for petvet project.
Generated by 'django-admin startproject' using Django 5.2.
"""

import os
from pathlib import Path
from datetime import timedelta

from dotenv import load_dotenv

load_dotenv()  # charge .env depuis la racine du projet backend/

BASE_DIR = Path(__file__).resolve().parent.parent
ROOT_URLCONF = 'petvet.urls'

# =============================================================================
# Sécurité de base
# =============================================================================

SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("La variable SECRET_KEY est obligatoire dans .env")

DEBUG = os.getenv("DEBUG", "True").lower() in ("true", "1", "yes", "t")

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

if DEBUG:
    ALLOWED_HOSTS.append("*")           # pratique en développement local
else:
    # En production : mets tes domaines réels
    # ALLOWED_HOSTS = ["api.tondomaine.com", "tondomaine.com"]
    pass


# =============================================================================
# Applications installées
# =============================================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # packages tiers
    "rest_framework",
    "corsheaders",
    "drf_yasg",  # swagger / redoc
    # tes applications
    "accounts",
    "pets",
    "appointments",
    "adoption",
    "products",
    #"orders",
]


# =============================================================================
# Middleware
# =============================================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # doit être haut dans la liste
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =============================================================================
# CORS – très important pour React/Vite
# =============================================================================

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        # Ajoute ici les origines autorisées en production
        # "https://ton-frontend.vercel.app",
        # "https://www.tondomaine.com",
    ]
    CORS_ALLOW_CREDENTIALS = True


# =============================================================================
# REST Framework
# =============================================================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        # Décommente si tu veux passer à JWT (plus moderne)
        # "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
        # En production tu peux passer à :
        # "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}


# =============================================================================
# Base de données MySQL
# =============================================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME", "cheebo"),
        "USER": os.getenv("DB_USER", "root"),
        "PASSWORD": os.getenv("DB_PASSWORD", "123456"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# =============================================================================
# Utilisateur personnalisé
# =============================================================================

AUTH_USER_MODEL = "accounts.CustomUser"


# =============================================================================
# Internationalisation & fuseau horaire (Tunisie)
# =============================================================================

LANGUAGE_CODE = "fr-fr"
TIME_ZONE = "Africa/Tunis"
USE_I18N = True
USE_TZ = True


# =============================================================================
# Fichiers statiques et médias (photos de profils, animaux, produits…)
# =============================================================================

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# =============================================================================
# Sécurité – à activer en production
# =============================================================================

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True


# =============================================================================
# Simple JWT (optionnel – à décommenter si tu veux l'utiliser)
# =============================================================================

# SIMPLE_JWT = {
#     "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
#     "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
#     "ROTATE_REFRESH_TOKENS": True,
#     "BLACKLIST_AFTER_ROTATION": True,
#     "UPDATE_LAST_LOGIN": True,
# }


# =============================================================================
# Autres réglages utiles
# =============================================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Redirections après login/logout (utile si tu utilises les vues Django classiques)
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


# =============================================================================
# Swagger / drf-yasg (optionnel)
# =============================================================================

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "api_key": {"type": "apiKey", "in": "header", "name": "Authorization"}
    },
}
# =============================================================================
# Templates (obligatoire pour l'admin Django)
# =============================================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],                     # Tu peux ajouter [BASE_DIR / 'templates'] si tu crées un dossier templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]